// Generated by scripts/prepare-subgraph.mjs — do not edit by hand.
import { Address } from "@graphprotocol/graph-ts";

export const CRYPTOPETS_ADDRESS = Address.fromString("0xd68c951132fda610062a03252d303f80cdb2379f");
