import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { describe, it } from "node:test";
import { fileURLToPath } from "node:url";

import { network } from "hardhat";

// Cross-chain parity fixture (plan §7): contracts/test-vectors/battle.json is generated by
// scripts/gen-battle-vectors.ts and re-checked here against CombatSimV1.simulate. The same
// file is the reference for combat::simulate on Solana and for indexer-go.

const __dirname = path.dirname(fileURLToPath(import.meta.url));

interface VectorCase {
    name: string;
    dna1: string;
    rarity1: number;
    level1: number;
    skill1: number;
    dna2: string;
    rarity2: number;
    level2: number;
    skill2: number;
    seed: string;
    expected: {
        firstWins: boolean;
        rounds: number;
        winnerHpRemaining: number;
    };
}

const fixture = JSON.parse(
    fs.readFileSync(path.resolve(__dirname, "../../test-vectors/battle.json"), "utf-8")
) as { skillConfig: Record<string, number>; cases: VectorCase[] };

describe("CombatSimV1 golden vectors (plan §7)", async function () {
    const { viem } = await network.connect();

    for (const c of fixture.cases) {
        it(`matches recorded result for "${c.name}"`, async function () {
            const combatSim = await viem.deployContract("CombatSimV1");

            const result = await combatSim.read.simulate([
                BigInt(c.dna1), c.rarity1, c.level1, c.skill1,
                BigInt(c.dna2), c.rarity2, c.level2, c.skill2,
                BigInt(c.seed), fixture.skillConfig,
            ]);

            assert.equal(result.firstWins, c.expected.firstWins, "firstWins");
            assert.equal(result.rounds, c.expected.rounds, "rounds");
            assert.equal(result.winnerHpRemaining, c.expected.winnerHpRemaining, "winnerHpRemaining");
        });
    }
});
