/**
 * Writes contracts/test-vectors/equipment.json (roadmap §4).
 *
 * Run with `pnpm --filter @cryptopets/protocol vectors:equipment`.
 *
 * **Regenerating to make a failing test pass is forbidden** (`AGENTS.md`), the same rule
 * gen-vectors.ts carries. These cases lock what equipment does to a fight, and both live
 * combat ports are held to them. A failure means a port drifted; fix the port.
 *
 * Deliberately a separate file from battle.json rather than more cases inside it.
 * battle.json is unchanged and still gates the ungeared engine, and the first case here
 * reproduces one of its rows exactly, which is what proves the modifier path costs an
 * ungeared fight nothing.
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { type AttrBonus, DEFAULT_SKILL_CONFIG, NO_BONUS, simulate } from '../src/combat';

/** Cases chosen to pin a property each, not to pad a count. */
const CASES: {
    name: string;
    note: string;
    dna1: string; rarity1: number; level1: number; skill1: number; bonus1: AttrBonus;
    dna2: string; rarity2: number; level2: number; skill2: number; bonus2: AttrBonus;
    seed: string;
}[] = [
    {
        name: 'ungeared-matches-battle-json',
        note: 'Both pets bare, with the same inputs as battle.json\'s baseline-no-skill. Must reproduce that case exactly: adding the modifier path cannot change an ungeared fight.',
        dna1: '1234567890123456', rarity1: 1, level1: 20, skill1: 99, bonus1: NO_BONUS,
        dna2: '9876543210987654', rarity2: 1, level2: 20, skill2: 99, bonus2: NO_BONUS,
        seed: '1',
    },
    {
        name: 'attacker-weapon',
        note: 'Attacker carries +4 ATK. Pins that a bonus on one side reaches the fight at all.',
        dna1: '1234567890123456', rarity1: 1, level1: 20, skill1: 99, bonus1: { ...NO_BONUS, atk: 4 },
        dna2: '9876543210987654', rarity2: 1, level2: 20, skill2: 99, bonus2: NO_BONUS,
        seed: '1',
    },
    {
        name: 'defender-armor',
        note: 'Defender carries +30 HP and +10 DEF. Pins that the two sides are not interchangeable.',
        dna1: '1234567890123456', rarity1: 1, level1: 20, skill1: 99, bonus1: NO_BONUS,
        dna2: '9876543210987654', rarity2: 1, level2: 20, skill2: 99, bonus2: { ...NO_BONUS, hp: 30, def: 10 },
        seed: '1',
    },
    {
        name: 'both-geared-full-set',
        note: 'Both sides wearing all three slots. Pins the summed-bonus path across every attribute.',
        dna1: '1234567890123456', rarity1: 1, level1: 20, skill1: 99,
        bonus1: { hp: 12, atk: 4, def: 4, int: 0, mdef: 0 },
        dna2: '9876543210987654', rarity2: 1, level2: 20, skill2: 99,
        bonus2: { hp: 45, atk: 0, def: 16, int: 12, mdef: 14 },
        seed: '1',
    },
    {
        name: 'gear-before-tank',
        note: 'Tank (skill 0) with +45 HP of armour. Pins the ordering: gear applies before the skill multiplier, so Tank\'s +20% multiplies the geared total. Applying it after would give a different HP and a different fight.',
        dna1: '1234567890123456', rarity1: 1, level1: 20, skill1: 0, bonus1: { ...NO_BONUS, hp: 45 },
        dna2: '9876543210987654', rarity2: 1, level2: 20, skill2: 99, bonus2: NO_BONUS,
        seed: '1',
    },
    {
        name: 'gear-before-shell',
        note: 'Shell (skill 2) with +16 DEF. The DEF equivalent of the case above, and Shell also drives initiative, so a reorder shows up in the strike order too.',
        dna1: '1234567890123456', rarity1: 1, level1: 20, skill1: 2, bonus1: { ...NO_BONUS, def: 16 },
        dna2: '9876543210987654', rarity2: 1, level2: 20, skill2: 99, bonus2: NO_BONUS,
        seed: '1',
    },
    {
        name: 'int-bonus-flips-initiative',
        note: 'Attacker gains +200 INT against an otherwise identical pet. INT decides who strikes first, so this pins that gear can change initiative and not merely damage.',
        dna1: '1234567890123456', rarity1: 1, level1: 20, skill1: 99, bonus1: { ...NO_BONUS, int: 200 },
        dna2: '1234567890123456', rarity2: 1, level2: 20, skill2: 99, bonus2: NO_BONUS,
        seed: '7',
    },
    {
        name: 'clamped-at-u16',
        note: 'An absurd +65535 HP bonus. Pins the clamp: the total saturates at 65535 rather than wrapping, because a wrapping addition would turn a well-geared pet into a nearly dead one at 65536.',
        dna1: '1234567890123456', rarity1: 5, level1: 100, skill1: 99, bonus1: { ...NO_BONUS, hp: 65535 },
        dna2: '9876543210987654', rarity2: 1, level2: 20, skill2: 99, bonus2: NO_BONUS,
        seed: '3',
    },
];

const doc = {
    description:
        'Equipment combat vectors (roadmap §4). Generated by protocol/scripts/gen-equipment-vectors.ts from protocol/src/combat. Separate from battle.json, which is unchanged and still gates the ungeared engine: these pin what equipment adds. Both live ports (protocol/src/combat and services/indexer-go/internal/combat) must reproduce every case. A failure means a port drifted; fix the port, never the vector.',
    skillConfig: DEFAULT_SKILL_CONFIG,
    cases: CASES.map((c) => {
        const outcome = simulate(
            BigInt(c.dna1), c.rarity1, c.level1, c.skill1,
            BigInt(c.dna2), c.rarity2, c.level2, c.skill2,
            BigInt(c.seed), DEFAULT_SKILL_CONFIG, c.bonus1, c.bonus2,
        );
        return {
            ...c,
            expected: {
                firstWins: outcome.result.firstWins,
                rounds: outcome.result.rounds,
                winnerHpRemaining: outcome.result.winnerHpRemaining,
                startHp1: Number(outcome.startHp1),
                startHp2: Number(outcome.startHp2),
            },
        };
    }),
};

const out = join(process.cwd(), '../contracts/test-vectors/equipment.json');
writeFileSync(out, `${JSON.stringify(doc, null, 2)}\n`);
console.log('wrote', out);
for (const c of doc.cases) console.log(' ', c.name, JSON.stringify(c.expected));
