packages:
  - 'frontend'
  - 'website'
  - 'backend'
  - 'mobile'
  - 'shared'
  - 'contracts/ethereum'
  - 'backend/graph/evm/subgraph'
  - 'backend/graph/solana/subgraph'
  - 'contracts/solana/cryptopets'
