packages:
  - 'frontend'
  - 'website'
  - 'services/backend'
  - 'mobile'
  - 'shared'
  - 'protocol'
  - 'verifier'
  - 'contracts/ethereum'
  - 'contracts/ethereum/subgraph'
  - 'contracts/solana/cryptopets'
