// Shared contract between indexer-go (server) and the Node backend (client).
// Node loads this file at runtime via @grpc/proto-loader; Go stubs are
// generated into indexer-go/pb with `buf generate` (see indexer-go/buf.gen.yaml).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cryptopets.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resume point per chain so a reconnecting client misses nothing:
	// chain -> last seen version (Solana slot / EVM block timestamp).
	// Missing chains replay nothing and stream live-only.
	AfterVersion  map[string]uint64 `protobuf:"bytes,1,rep,name=after_version,json=afterVersion,proto3" json:"after_version,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_cryptopets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cryptopets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_cryptopets_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetAfterVersion() map[string]uint64 {
	if x != nil {
		return x.AfterVersion
	}
	return nil
}

type BattleEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         string                 `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`                       // "evm" | "solana"
	BattleId      string                 `protobuf:"bytes,2,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"` // settle sig (solana) / txHash-logIndex (evm)
	AttackerPet   string                 `protobuf:"bytes,3,opt,name=attacker_pet,json=attackerPet,proto3" json:"attacker_pet,omitempty"`
	DefenderPet   string                 `protobuf:"bytes,4,opt,name=defender_pet,json=defenderPet,proto3" json:"defender_pet,omitempty"`
	WinnerPet     string                 `protobuf:"bytes,5,opt,name=winner_pet,json=winnerPet,proto3" json:"winner_pet,omitempty"` // absolute pet id — matches battle_history.winner_pet_id
	Version       uint64                 `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`                     // feed back as after_version on reconnect
	FoughtAt      int64                  `protobuf:"varint,7,opt,name=fought_at,json=foughtAt,proto3" json:"fought_at,omitempty"`   // unix seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleEvent) Reset() {
	*x = BattleEvent{}
	mi := &file_cryptopets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleEvent) ProtoMessage() {}

func (x *BattleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cryptopets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleEvent.ProtoReflect.Descriptor instead.
func (*BattleEvent) Descriptor() ([]byte, []int) {
	return file_cryptopets_proto_rawDescGZIP(), []int{1}
}

func (x *BattleEvent) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *BattleEvent) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *BattleEvent) GetAttackerPet() string {
	if x != nil {
		return x.AttackerPet
	}
	return ""
}

func (x *BattleEvent) GetDefenderPet() string {
	if x != nil {
		return x.DefenderPet
	}
	return ""
}

func (x *BattleEvent) GetWinnerPet() string {
	if x != nil {
		return x.WinnerPet
	}
	return ""
}

func (x *BattleEvent) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BattleEvent) GetFoughtAt() int64 {
	if x != nil {
		return x.FoughtAt
	}
	return 0
}

var File_cryptopets_proto protoreflect.FileDescriptor

const file_cryptopets_proto_rawDesc = "" +
	"\n" +
	"\x10cryptopets.proto\x12\n" +
	"cryptopets\"\xa2\x01\n" +
	"\rStreamRequest\x12P\n" +
	"\rafter_version\x18\x01 \x03(\v2+.cryptopets.StreamRequest.AfterVersionEntryR\fafterVersion\x1a?\n" +
	"\x11AfterVersionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\xdc\x01\n" +
	"\vBattleEvent\x12\x14\n" +
	"\x05chain\x18\x01 \x01(\tR\x05chain\x12\x1b\n" +
	"\tbattle_id\x18\x02 \x01(\tR\bbattleId\x12!\n" +
	"\fattacker_pet\x18\x03 \x01(\tR\vattackerPet\x12!\n" +
	"\fdefender_pet\x18\x04 \x01(\tR\vdefenderPet\x12\x1d\n" +
	"\n" +
	"winner_pet\x18\x05 \x01(\tR\twinnerPet\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x04R\aversion\x12\x1b\n" +
	"\tfought_at\x18\a \x01(\x03R\bfoughtAt2\\\n" +
	"\x0fGameDataService\x12I\n" +
	"\x11StreamLiveBattles\x12\x19.cryptopets.StreamRequest\x1a\x17.cryptopets.BattleEvent0\x01B.Z,github.com/radcrew/do-not-stop/indexer-go/pbb\x06proto3"

var (
	file_cryptopets_proto_rawDescOnce sync.Once
	file_cryptopets_proto_rawDescData []byte
)

func file_cryptopets_proto_rawDescGZIP() []byte {
	file_cryptopets_proto_rawDescOnce.Do(func() {
		file_cryptopets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cryptopets_proto_rawDesc), len(file_cryptopets_proto_rawDesc)))
	})
	return file_cryptopets_proto_rawDescData
}

var file_cryptopets_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cryptopets_proto_goTypes = []any{
	(*StreamRequest)(nil), // 0: cryptopets.StreamRequest
	(*BattleEvent)(nil),   // 1: cryptopets.BattleEvent
	nil,                   // 2: cryptopets.StreamRequest.AfterVersionEntry
}
var file_cryptopets_proto_depIdxs = []int32{
	2, // 0: cryptopets.StreamRequest.after_version:type_name -> cryptopets.StreamRequest.AfterVersionEntry
	0, // 1: cryptopets.GameDataService.StreamLiveBattles:input_type -> cryptopets.StreamRequest
	1, // 2: cryptopets.GameDataService.StreamLiveBattles:output_type -> cryptopets.BattleEvent
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cryptopets_proto_init() }
func file_cryptopets_proto_init() {
	if File_cryptopets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cryptopets_proto_rawDesc), len(file_cryptopets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cryptopets_proto_goTypes,
		DependencyIndexes: file_cryptopets_proto_depIdxs,
		MessageInfos:      file_cryptopets_proto_msgTypes,
	}.Build()
	File_cryptopets_proto = out.File
	file_cryptopets_proto_goTypes = nil
	file_cryptopets_proto_depIdxs = nil
}
