// Shared contract between indexer-go (server) and the Node backend (client).
// Node loads this file at runtime via @grpc/proto-loader; Go stubs are
// generated into indexer-go/pb with `buf generate` (see indexer-go/buf.gen.yaml).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cryptopets.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         string                 `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	PetId         string                 `protobuf:"bytes,2,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetRequest) Reset() {
	*x = PetRequest{}
	mi := &file_cryptopets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetRequest) ProtoMessage() {}

func (x *PetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cryptopets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetRequest.ProtoReflect.Descriptor instead.
func (*PetRequest) Descriptor() ([]byte, []int) {
	return file_cryptopets_proto_rawDescGZIP(), []int{0}
}

func (x *PetRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *PetRequest) GetPetId() string {
	if x != nil {
		return x.PetId
	}
	return ""
}

type PetResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Chain     string                 `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	PetId     string                 `protobuf:"bytes,2,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`
	Owner     string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Name      string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Level     uint32                 `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	Rarity    uint32                 `protobuf:"varint,6,opt,name=rarity,proto3" json:"rarity,omitempty"`
	Dna       string                 `protobuf:"bytes,7,opt,name=dna,proto3" json:"dna,omitempty"` // bigint as string, matching pet_roster.dna
	WinCount  uint32                 `protobuf:"varint,8,opt,name=win_count,json=winCount,proto3" json:"win_count,omitempty"`
	LossCount uint32                 `protobuf:"varint,9,opt,name=loss_count,json=lossCount,proto3" json:"loss_count,omitempty"`
	ReadyAt   int64                  `protobuf:"varint,10,opt,name=ready_at,json=readyAt,proto3" json:"ready_at,omitempty"` // unix seconds the pet is next BATTLE-ready
	Version   uint64                 `protobuf:"varint,11,opt,name=version,proto3" json:"version,omitempty"`
	// v2 fields (plan §3.4, §4.1, §3.7, §4.4, §2.3). Append-only field numbers so
	// a backend on the old proto keeps working.
	Xp            uint32 `protobuf:"varint,12,opt,name=xp,proto3" json:"xp,omitempty"`
	Generation    uint32 `protobuf:"varint,13,opt,name=generation,proto3" json:"generation,omitempty"`
	Parent1Id     string `protobuf:"bytes,14,opt,name=parent1_id,json=parent1Id,proto3" json:"parent1_id,omitempty"` // "0" = none
	Parent2Id     string `protobuf:"bytes,15,opt,name=parent2_id,json=parent2Id,proto3" json:"parent2_id,omitempty"`
	BreedCount    uint32 `protobuf:"varint,16,opt,name=breed_count,json=breedCount,proto3" json:"breed_count,omitempty"`
	SpeciesId     uint32 `protobuf:"varint,17,opt,name=species_id,json=speciesId,proto3" json:"species_id,omitempty"`
	SpouseId      string `protobuf:"bytes,18,opt,name=spouse_id,json=spouseId,proto3" json:"spouse_id,omitempty"`                // "0" = unmarried
	BreedReadyAt  int64  `protobuf:"varint,19,opt,name=breed_ready_at,json=breedReadyAt,proto3" json:"breed_ready_at,omitempty"` // unix seconds next breed-ready
	TrainReadyAt  int64  `protobuf:"varint,20,opt,name=train_ready_at,json=trainReadyAt,proto3" json:"train_ready_at,omitempty"` // unix seconds next train-ready
	Asset         string `protobuf:"bytes,21,opt,name=asset,proto3" json:"asset,omitempty"`                                      // Metaplex Core asset pubkey (Solana only); "" on EVM
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetResponse) Reset() {
	*x = PetResponse{}
	mi := &file_cryptopets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetResponse) ProtoMessage() {}

func (x *PetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cryptopets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetResponse.ProtoReflect.Descriptor instead.
func (*PetResponse) Descriptor() ([]byte, []int) {
	return file_cryptopets_proto_rawDescGZIP(), []int{1}
}

func (x *PetResponse) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *PetResponse) GetPetId() string {
	if x != nil {
		return x.PetId
	}
	return ""
}

func (x *PetResponse) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *PetResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PetResponse) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PetResponse) GetRarity() uint32 {
	if x != nil {
		return x.Rarity
	}
	return 0
}

func (x *PetResponse) GetDna() string {
	if x != nil {
		return x.Dna
	}
	return ""
}

func (x *PetResponse) GetWinCount() uint32 {
	if x != nil {
		return x.WinCount
	}
	return 0
}

func (x *PetResponse) GetLossCount() uint32 {
	if x != nil {
		return x.LossCount
	}
	return 0
}

func (x *PetResponse) GetReadyAt() int64 {
	if x != nil {
		return x.ReadyAt
	}
	return 0
}

func (x *PetResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PetResponse) GetXp() uint32 {
	if x != nil {
		return x.Xp
	}
	return 0
}

func (x *PetResponse) GetGeneration() uint32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *PetResponse) GetParent1Id() string {
	if x != nil {
		return x.Parent1Id
	}
	return ""
}

func (x *PetResponse) GetParent2Id() string {
	if x != nil {
		return x.Parent2Id
	}
	return ""
}

func (x *PetResponse) GetBreedCount() uint32 {
	if x != nil {
		return x.BreedCount
	}
	return 0
}

func (x *PetResponse) GetSpeciesId() uint32 {
	if x != nil {
		return x.SpeciesId
	}
	return 0
}

func (x *PetResponse) GetSpouseId() string {
	if x != nil {
		return x.SpouseId
	}
	return ""
}

func (x *PetResponse) GetBreedReadyAt() int64 {
	if x != nil {
		return x.BreedReadyAt
	}
	return 0
}

func (x *PetResponse) GetTrainReadyAt() int64 {
	if x != nil {
		return x.TrainReadyAt
	}
	return 0
}

func (x *PetResponse) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

type OpponentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         string                 `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	ExcludeOwner  string                 `protobuf:"bytes,2,opt,name=exclude_owner,json=excludeOwner,proto3" json:"exclude_owner,omitempty"` // normalized address / pubkey
	MinLevel      uint32                 `protobuf:"varint,3,opt,name=min_level,json=minLevel,proto3" json:"min_level,omitempty"`
	Page          uint32                 `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpponentsRequest) Reset() {
	*x = OpponentsRequest{}
	mi := &file_cryptopets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpponentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpponentsRequest) ProtoMessage() {}

func (x *OpponentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cryptopets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpponentsRequest.ProtoReflect.Descriptor instead.
func (*OpponentsRequest) Descriptor() ([]byte, []int) {
	return file_cryptopets_proto_rawDescGZIP(), []int{2}
}

func (x *OpponentsRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *OpponentsRequest) GetExcludeOwner() string {
	if x != nil {
		return x.ExcludeOwner
	}
	return ""
}

func (x *OpponentsRequest) GetMinLevel() uint32 {
	if x != nil {
		return x.MinLevel
	}
	return 0
}

func (x *OpponentsRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *OpponentsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type OpponentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pets          []*PetResponse         `protobuf:"bytes,1,rep,name=pets,proto3" json:"pets,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // total matches before paging (pagination parity)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpponentsResponse) Reset() {
	*x = OpponentsResponse{}
	mi := &file_cryptopets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpponentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpponentsResponse) ProtoMessage() {}

func (x *OpponentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cryptopets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpponentsResponse.ProtoReflect.Descriptor instead.
func (*OpponentsResponse) Descriptor() ([]byte, []int) {
	return file_cryptopets_proto_rawDescGZIP(), []int{3}
}

func (x *OpponentsResponse) GetPets() []*PetResponse {
	if x != nil {
		return x.Pets
	}
	return nil
}

func (x *OpponentsResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type WinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         string                 `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	PetId1        string                 `protobuf:"bytes,2,opt,name=pet_id1,json=petId1,proto3" json:"pet_id1,omitempty"` // the pet whose win probability is returned
	PetId2        string                 `protobuf:"bytes,3,opt,name=pet_id2,json=petId2,proto3" json:"pet_id2,omitempty"` // the opponent
	Samples       uint32                 `protobuf:"varint,4,opt,name=samples,proto3" json:"samples,omitempty"`            // seeds to sample; 0 = server default
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WinRequest) Reset() {
	*x = WinRequest{}
	mi := &file_cryptopets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WinRequest) ProtoMessage() {}

func (x *WinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cryptopets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WinRequest.ProtoReflect.Descriptor instead.
func (*WinRequest) Descriptor() ([]byte, []int) {
	return file_cryptopets_proto_rawDescGZIP(), []int{4}
}

func (x *WinRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *WinRequest) GetPetId1() string {
	if x != nil {
		return x.PetId1
	}
	return ""
}

func (x *WinRequest) GetPetId2() string {
	if x != nil {
		return x.PetId2
	}
	return ""
}

func (x *WinRequest) GetSamples() uint32 {
	if x != nil {
		return x.Samples
	}
	return 0
}

type WinResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WinProbability float64                `protobuf:"fixed64,1,opt,name=win_probability,json=winProbability,proto3" json:"win_probability,omitempty"` // pet_id1's win probability in [0,1]
	Samples        uint32                 `protobuf:"varint,2,opt,name=samples,proto3" json:"samples,omitempty"`                                      // seeds actually sampled
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WinResponse) Reset() {
	*x = WinResponse{}
	mi := &file_cryptopets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WinResponse) ProtoMessage() {}

func (x *WinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cryptopets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WinResponse.ProtoReflect.Descriptor instead.
func (*WinResponse) Descriptor() ([]byte, []int) {
	return file_cryptopets_proto_rawDescGZIP(), []int{5}
}

func (x *WinResponse) GetWinProbability() float64 {
	if x != nil {
		return x.WinProbability
	}
	return 0
}

func (x *WinResponse) GetSamples() uint32 {
	if x != nil {
		return x.Samples
	}
	return 0
}

type StreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resume point per chain so a reconnecting client misses nothing:
	// chain -> last seen version (Solana slot / EVM block timestamp).
	// Missing chains replay nothing and stream live-only.
	AfterVersion  map[string]uint64 `protobuf:"bytes,1,rep,name=after_version,json=afterVersion,proto3" json:"after_version,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_cryptopets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cryptopets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_cryptopets_proto_rawDescGZIP(), []int{6}
}

func (x *StreamRequest) GetAfterVersion() map[string]uint64 {
	if x != nil {
		return x.AfterVersion
	}
	return nil
}

type BattleEvent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Chain       string                 `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`                       // "evm" | "solana"
	BattleId    string                 `protobuf:"bytes,2,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"` // settle sig (solana) / txHash-logIndex (evm)
	AttackerPet string                 `protobuf:"bytes,3,opt,name=attacker_pet,json=attackerPet,proto3" json:"attacker_pet,omitempty"`
	DefenderPet string                 `protobuf:"bytes,4,opt,name=defender_pet,json=defenderPet,proto3" json:"defender_pet,omitempty"`
	WinnerPet   string                 `protobuf:"bytes,5,opt,name=winner_pet,json=winnerPet,proto3" json:"winner_pet,omitempty"` // absolute pet id — matches battle_history.winner_pet_id
	Version     uint64                 `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`                     // feed back as after_version on reconnect
	FoughtAt    int64                  `protobuf:"varint,7,opt,name=fought_at,json=foughtAt,proto3" json:"fought_at,omitempty"`   // unix seconds
	// v2 round-based combat sim outputs (plan §3.3). Append-only field numbers.
	LoserPet          string `protobuf:"bytes,8,opt,name=loser_pet,json=loserPet,proto3" json:"loser_pet,omitempty"` // absolute pet id of the loser
	Seed              string `protobuf:"bytes,9,opt,name=seed,proto3" json:"seed,omitempty"`                         // 0x-hex 32-byte combat seed; replays the sim off-chain
	Rounds            uint32 `protobuf:"varint,10,opt,name=rounds,proto3" json:"rounds,omitempty"`
	WinnerHpRemaining uint32 `protobuf:"varint,11,opt,name=winner_hp_remaining,json=winnerHpRemaining,proto3" json:"winner_hp_remaining,omitempty"`
	XpWin             uint32 `protobuf:"varint,12,opt,name=xp_win,json=xpWin,proto3" json:"xp_win,omitempty"`
	XpLoss            uint32 `protobuf:"varint,13,opt,name=xp_loss,json=xpLoss,proto3" json:"xp_loss,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BattleEvent) Reset() {
	*x = BattleEvent{}
	mi := &file_cryptopets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleEvent) ProtoMessage() {}

func (x *BattleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cryptopets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleEvent.ProtoReflect.Descriptor instead.
func (*BattleEvent) Descriptor() ([]byte, []int) {
	return file_cryptopets_proto_rawDescGZIP(), []int{7}
}

func (x *BattleEvent) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *BattleEvent) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *BattleEvent) GetAttackerPet() string {
	if x != nil {
		return x.AttackerPet
	}
	return ""
}

func (x *BattleEvent) GetDefenderPet() string {
	if x != nil {
		return x.DefenderPet
	}
	return ""
}

func (x *BattleEvent) GetWinnerPet() string {
	if x != nil {
		return x.WinnerPet
	}
	return ""
}

func (x *BattleEvent) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BattleEvent) GetFoughtAt() int64 {
	if x != nil {
		return x.FoughtAt
	}
	return 0
}

func (x *BattleEvent) GetLoserPet() string {
	if x != nil {
		return x.LoserPet
	}
	return ""
}

func (x *BattleEvent) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

func (x *BattleEvent) GetRounds() uint32 {
	if x != nil {
		return x.Rounds
	}
	return 0
}

func (x *BattleEvent) GetWinnerHpRemaining() uint32 {
	if x != nil {
		return x.WinnerHpRemaining
	}
	return 0
}

func (x *BattleEvent) GetXpWin() uint32 {
	if x != nil {
		return x.XpWin
	}
	return 0
}

func (x *BattleEvent) GetXpLoss() uint32 {
	if x != nil {
		return x.XpLoss
	}
	return 0
}

var File_cryptopets_proto protoreflect.FileDescriptor

const file_cryptopets_proto_rawDesc = "" +
	"\n" +
	"\x10cryptopets.proto\x12\n" +
	"cryptopets\"9\n" +
	"\n" +
	"PetRequest\x12\x14\n" +
	"\x05chain\x18\x01 \x01(\tR\x05chain\x12\x15\n" +
	"\x06pet_id\x18\x02 \x01(\tR\x05petId\"\xc2\x04\n" +
	"\vPetResponse\x12\x14\n" +
	"\x05chain\x18\x01 \x01(\tR\x05chain\x12\x15\n" +
	"\x06pet_id\x18\x02 \x01(\tR\x05petId\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x05 \x01(\rR\x05level\x12\x16\n" +
	"\x06rarity\x18\x06 \x01(\rR\x06rarity\x12\x10\n" +
	"\x03dna\x18\a \x01(\tR\x03dna\x12\x1b\n" +
	"\twin_count\x18\b \x01(\rR\bwinCount\x12\x1d\n" +
	"\n" +
	"loss_count\x18\t \x01(\rR\tlossCount\x12\x19\n" +
	"\bready_at\x18\n" +
	" \x01(\x03R\areadyAt\x12\x18\n" +
	"\aversion\x18\v \x01(\x04R\aversion\x12\x0e\n" +
	"\x02xp\x18\f \x01(\rR\x02xp\x12\x1e\n" +
	"\n" +
	"generation\x18\r \x01(\rR\n" +
	"generation\x12\x1d\n" +
	"\n" +
	"parent1_id\x18\x0e \x01(\tR\tparent1Id\x12\x1d\n" +
	"\n" +
	"parent2_id\x18\x0f \x01(\tR\tparent2Id\x12\x1f\n" +
	"\vbreed_count\x18\x10 \x01(\rR\n" +
	"breedCount\x12\x1d\n" +
	"\n" +
	"species_id\x18\x11 \x01(\rR\tspeciesId\x12\x1b\n" +
	"\tspouse_id\x18\x12 \x01(\tR\bspouseId\x12$\n" +
	"\x0ebreed_ready_at\x18\x13 \x01(\x03R\fbreedReadyAt\x12$\n" +
	"\x0etrain_ready_at\x18\x14 \x01(\x03R\ftrainReadyAt\x12\x14\n" +
	"\x05asset\x18\x15 \x01(\tR\x05asset\"\x9b\x01\n" +
	"\x10OpponentsRequest\x12\x14\n" +
	"\x05chain\x18\x01 \x01(\tR\x05chain\x12#\n" +
	"\rexclude_owner\x18\x02 \x01(\tR\fexcludeOwner\x12\x1b\n" +
	"\tmin_level\x18\x03 \x01(\rR\bminLevel\x12\x12\n" +
	"\x04page\x18\x04 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\rR\bpageSize\"V\n" +
	"\x11OpponentsResponse\x12+\n" +
	"\x04pets\x18\x01 \x03(\v2\x17.cryptopets.PetResponseR\x04pets\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\"n\n" +
	"\n" +
	"WinRequest\x12\x14\n" +
	"\x05chain\x18\x01 \x01(\tR\x05chain\x12\x17\n" +
	"\apet_id1\x18\x02 \x01(\tR\x06petId1\x12\x17\n" +
	"\apet_id2\x18\x03 \x01(\tR\x06petId2\x12\x18\n" +
	"\asamples\x18\x04 \x01(\rR\asamples\"P\n" +
	"\vWinResponse\x12'\n" +
	"\x0fwin_probability\x18\x01 \x01(\x01R\x0ewinProbability\x12\x18\n" +
	"\asamples\x18\x02 \x01(\rR\asamples\"\xa2\x01\n" +
	"\rStreamRequest\x12P\n" +
	"\rafter_version\x18\x01 \x03(\v2+.cryptopets.StreamRequest.AfterVersionEntryR\fafterVersion\x1a?\n" +
	"\x11AfterVersionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\x85\x03\n" +
	"\vBattleEvent\x12\x14\n" +
	"\x05chain\x18\x01 \x01(\tR\x05chain\x12\x1b\n" +
	"\tbattle_id\x18\x02 \x01(\tR\bbattleId\x12!\n" +
	"\fattacker_pet\x18\x03 \x01(\tR\vattackerPet\x12!\n" +
	"\fdefender_pet\x18\x04 \x01(\tR\vdefenderPet\x12\x1d\n" +
	"\n" +
	"winner_pet\x18\x05 \x01(\tR\twinnerPet\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x04R\aversion\x12\x1b\n" +
	"\tfought_at\x18\a \x01(\x03R\bfoughtAt\x12\x1b\n" +
	"\tloser_pet\x18\b \x01(\tR\bloserPet\x12\x12\n" +
	"\x04seed\x18\t \x01(\tR\x04seed\x12\x16\n" +
	"\x06rounds\x18\n" +
	" \x01(\rR\x06rounds\x12.\n" +
	"\x13winner_hp_remaining\x18\v \x01(\rR\x11winnerHpRemaining\x12\x15\n" +
	"\x06xp_win\x18\f \x01(\rR\x05xpWin\x12\x17\n" +
	"\axp_loss\x18\r \x01(\rR\x06xpLoss2\xaf\x02\n" +
	"\x0fGameDataService\x12I\n" +
	"\x11StreamLiveBattles\x12\x19.cryptopets.StreamRequest\x1a\x17.cryptopets.BattleEvent0\x01\x12>\n" +
	"\vGetPetState\x12\x16.cryptopets.PetRequest\x1a\x17.cryptopets.PetResponse\x12Q\n" +
	"\x12ListReadyOpponents\x12\x1c.cryptopets.OpponentsRequest\x1a\x1d.cryptopets.OpponentsResponse\x12>\n" +
	"\vEstimateWin\x12\x16.cryptopets.WinRequest\x1a\x17.cryptopets.WinResponseB.Z,github.com/radcrew/do-not-stop/indexer-go/pbb\x06proto3"

var (
	file_cryptopets_proto_rawDescOnce sync.Once
	file_cryptopets_proto_rawDescData []byte
)

func file_cryptopets_proto_rawDescGZIP() []byte {
	file_cryptopets_proto_rawDescOnce.Do(func() {
		file_cryptopets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cryptopets_proto_rawDesc), len(file_cryptopets_proto_rawDesc)))
	})
	return file_cryptopets_proto_rawDescData
}

var file_cryptopets_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_cryptopets_proto_goTypes = []any{
	(*PetRequest)(nil),        // 0: cryptopets.PetRequest
	(*PetResponse)(nil),       // 1: cryptopets.PetResponse
	(*OpponentsRequest)(nil),  // 2: cryptopets.OpponentsRequest
	(*OpponentsResponse)(nil), // 3: cryptopets.OpponentsResponse
	(*WinRequest)(nil),        // 4: cryptopets.WinRequest
	(*WinResponse)(nil),       // 5: cryptopets.WinResponse
	(*StreamRequest)(nil),     // 6: cryptopets.StreamRequest
	(*BattleEvent)(nil),       // 7: cryptopets.BattleEvent
	nil,                       // 8: cryptopets.StreamRequest.AfterVersionEntry
}
var file_cryptopets_proto_depIdxs = []int32{
	1, // 0: cryptopets.OpponentsResponse.pets:type_name -> cryptopets.PetResponse
	8, // 1: cryptopets.StreamRequest.after_version:type_name -> cryptopets.StreamRequest.AfterVersionEntry
	6, // 2: cryptopets.GameDataService.StreamLiveBattles:input_type -> cryptopets.StreamRequest
	0, // 3: cryptopets.GameDataService.GetPetState:input_type -> cryptopets.PetRequest
	2, // 4: cryptopets.GameDataService.ListReadyOpponents:input_type -> cryptopets.OpponentsRequest
	4, // 5: cryptopets.GameDataService.EstimateWin:input_type -> cryptopets.WinRequest
	7, // 6: cryptopets.GameDataService.StreamLiveBattles:output_type -> cryptopets.BattleEvent
	1, // 7: cryptopets.GameDataService.GetPetState:output_type -> cryptopets.PetResponse
	3, // 8: cryptopets.GameDataService.ListReadyOpponents:output_type -> cryptopets.OpponentsResponse
	5, // 9: cryptopets.GameDataService.EstimateWin:output_type -> cryptopets.WinResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cryptopets_proto_init() }
func file_cryptopets_proto_init() {
	if File_cryptopets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cryptopets_proto_rawDesc), len(file_cryptopets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cryptopets_proto_goTypes,
		DependencyIndexes: file_cryptopets_proto_depIdxs,
		MessageInfos:      file_cryptopets_proto_msgTypes,
	}.Build()
	File_cryptopets_proto = out.File
	file_cryptopets_proto_goTypes = nil
	file_cryptopets_proto_depIdxs = nil
}
