// Shared contract between indexer-go (server) and the Node backend (client).
// Node loads this file at runtime via @grpc/proto-loader; Go stubs are
// generated into indexer-go/pb with `buf generate` (see indexer-go/buf.gen.yaml).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: cryptopets.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameDataService_StreamLiveBattles_FullMethodName  = "/cryptopets.GameDataService/StreamLiveBattles"
	GameDataService_GetPetState_FullMethodName        = "/cryptopets.GameDataService/GetPetState"
	GameDataService_ListReadyOpponents_FullMethodName = "/cryptopets.GameDataService/ListReadyOpponents"
)

// GameDataServiceClient is the client API for GameDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameDataServiceClient interface {
	// Server streaming: indexer-go pushes settled battles (both chains) the
	// moment they index. Delivery is at-least-once — consumers must be
	// idempotent by (chain, battle_id).
	StreamLiveBattles(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BattleEvent], error)
	// RAM reads from the write-through roster cache (coherent because
	// indexer-go is the sole writer of pet_roster after promotion). Both
	// return UNAVAILABLE until warm-up completes — callers fall back to
	// their own database read.
	GetPetState(ctx context.Context, in *PetRequest, opts ...grpc.CallOption) (*PetResponse, error)
	// Mirrors the backend's findReadyOpponents matchmaking query:
	// battle-ready (ready_at <= now), not owned by the caller, optional
	// minimum level, ordered by (level, pet_id), paged.
	ListReadyOpponents(ctx context.Context, in *OpponentsRequest, opts ...grpc.CallOption) (*OpponentsResponse, error)
}

type gameDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameDataServiceClient(cc grpc.ClientConnInterface) GameDataServiceClient {
	return &gameDataServiceClient{cc}
}

func (c *gameDataServiceClient) StreamLiveBattles(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BattleEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GameDataService_ServiceDesc.Streams[0], GameDataService_StreamLiveBattles_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, BattleEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameDataService_StreamLiveBattlesClient = grpc.ServerStreamingClient[BattleEvent]

func (c *gameDataServiceClient) GetPetState(ctx context.Context, in *PetRequest, opts ...grpc.CallOption) (*PetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PetResponse)
	err := c.cc.Invoke(ctx, GameDataService_GetPetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameDataServiceClient) ListReadyOpponents(ctx context.Context, in *OpponentsRequest, opts ...grpc.CallOption) (*OpponentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpponentsResponse)
	err := c.cc.Invoke(ctx, GameDataService_ListReadyOpponents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameDataServiceServer is the server API for GameDataService service.
// All implementations must embed UnimplementedGameDataServiceServer
// for forward compatibility.
type GameDataServiceServer interface {
	// Server streaming: indexer-go pushes settled battles (both chains) the
	// moment they index. Delivery is at-least-once — consumers must be
	// idempotent by (chain, battle_id).
	StreamLiveBattles(*StreamRequest, grpc.ServerStreamingServer[BattleEvent]) error
	// RAM reads from the write-through roster cache (coherent because
	// indexer-go is the sole writer of pet_roster after promotion). Both
	// return UNAVAILABLE until warm-up completes — callers fall back to
	// their own database read.
	GetPetState(context.Context, *PetRequest) (*PetResponse, error)
	// Mirrors the backend's findReadyOpponents matchmaking query:
	// battle-ready (ready_at <= now), not owned by the caller, optional
	// minimum level, ordered by (level, pet_id), paged.
	ListReadyOpponents(context.Context, *OpponentsRequest) (*OpponentsResponse, error)
	mustEmbedUnimplementedGameDataServiceServer()
}

// UnimplementedGameDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameDataServiceServer struct{}

func (UnimplementedGameDataServiceServer) StreamLiveBattles(*StreamRequest, grpc.ServerStreamingServer[BattleEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamLiveBattles not implemented")
}
func (UnimplementedGameDataServiceServer) GetPetState(context.Context, *PetRequest) (*PetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPetState not implemented")
}
func (UnimplementedGameDataServiceServer) ListReadyOpponents(context.Context, *OpponentsRequest) (*OpponentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListReadyOpponents not implemented")
}
func (UnimplementedGameDataServiceServer) mustEmbedUnimplementedGameDataServiceServer() {}
func (UnimplementedGameDataServiceServer) testEmbeddedByValue()                         {}

// UnsafeGameDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameDataServiceServer will
// result in compilation errors.
type UnsafeGameDataServiceServer interface {
	mustEmbedUnimplementedGameDataServiceServer()
}

func RegisterGameDataServiceServer(s grpc.ServiceRegistrar, srv GameDataServiceServer) {
	// If the following call panics, it indicates UnimplementedGameDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameDataService_ServiceDesc, srv)
}

func _GameDataService_StreamLiveBattles_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GameDataServiceServer).StreamLiveBattles(m, &grpc.GenericServerStream[StreamRequest, BattleEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameDataService_StreamLiveBattlesServer = grpc.ServerStreamingServer[BattleEvent]

func _GameDataService_GetPetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameDataServiceServer).GetPetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameDataService_GetPetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameDataServiceServer).GetPetState(ctx, req.(*PetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameDataService_ListReadyOpponents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpponentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameDataServiceServer).ListReadyOpponents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameDataService_ListReadyOpponents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameDataServiceServer).ListReadyOpponents(ctx, req.(*OpponentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameDataService_ServiceDesc is the grpc.ServiceDesc for GameDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cryptopets.GameDataService",
	HandlerType: (*GameDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPetState",
			Handler:    _GameDataService_GetPetState_Handler,
		},
		{
			MethodName: "ListReadyOpponents",
			Handler:    _GameDataService_ListReadyOpponents_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLiveBattles",
			Handler:       _GameDataService_StreamLiveBattles_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cryptopets.proto",
}
