services:
  # Solana development environment using pre-built image
  solana-dev:
    image: tchambard/solana-test-validator:latest
    container_name: solana-dev
    user: root
    ports:
      - "8899:8899" # RPC port
      - "8900:8900" # WebSocket port
      - "9900:9900" # Metrics port
    volumes:
      - ./cryptozombies:/home/ubuntu/cryptozombies
      - .pnpm-store:/home/ubuntu/.pnpm-store
      - solana-cache:/root/.cache/solana
    working_dir: /home/ubuntu
    command: >
      sh -c "
        pnpm config set store-dir /home/ubuntu/.pnpm-store &&
        solana-test-validator --reset --rpc-port 8899 --bind-address 0.0.0.0 --quiet > /dev/null 2>&1 &
        sleep 10 &&
        tail -f /dev/null
      "
    environment:
      - RUST_LOG=warn
      - TMPDIR=/tmp
    networks:
      - solana-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8899/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  solana-network:
    driver: bridge

volumes:
  solana-cache:
