-- AlterTable
ALTER TABLE "pet_roster" ADD COLUMN     "asset" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "breed_count" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "breed_ready_at" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN     "generation" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "parent1_id" TEXT NOT NULL DEFAULT '0',
ADD COLUMN     "parent2_id" TEXT NOT NULL DEFAULT '0',
ADD COLUMN     "species_id" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "spouse_id" TEXT NOT NULL DEFAULT '0',
ADD COLUMN     "train_ready_at" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN     "xp" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "battle_history" ADD COLUMN     "loser_pet_id" TEXT NOT NULL DEFAULT '0',
ADD COLUMN     "rounds" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "seed" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "winner_hp_remaining" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "xp_loss" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "xp_win" INTEGER NOT NULL DEFAULT 0;
