// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations/introspection use a direct (session-mode) connection — the
    // transaction-mode pooler in DATABASE_URL can't run DDL / advisory locks.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
