// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Pet {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="2")]
    pub owner: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub dna: ::prost::alloc::string::String,
    #[prost(uint32, tag="5")]
    pub level: u32,
    #[prost(uint32, tag="6")]
    pub rarity: u32,
    #[prost(uint32, tag="7")]
    pub win_count: u32,
    #[prost(uint32, tag="8")]
    pub loss_count: u32,
    #[prost(string, tag="9")]
    pub ready_at: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub updated_at: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Pets {
    #[prost(message, repeated, tag="1")]
    pub pets: ::prost::alloc::vec::Vec<Pet>,
}
// @@protoc_insertion_point(module)
