// @generated
// This file is @generated by prost-build.
/// Output of the imported `accounts:filtered_accounts` module — the input to
/// our `map_pets` handler. Vendored subset of `solana-accounts-foundational`.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FilteredAccounts {
    #[prost(message, repeated, tag="1")]
    pub accounts: ::prost::alloc::vec::Vec<super::super::super::super::solana::r#type::v1::Account>,
}
// @@protoc_insertion_point(module)
