// @generated
// This file is @generated by prost-build.
/// Vendored subset of the `solana-accounts-foundational` package
/// (<https://spkg.io/streamingfast/solana-accounts-foundational>). We redefine
/// only the message our mapping consumes so codegen stays minimal — the wire
/// format (field numbers/types) must match the upstream package exactly.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Account {
    #[prost(bytes="vec", tag="1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub owner: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="4")]
    pub source_slot: u64,
    #[prost(uint64, tag="5")]
    pub rent_epoch: u64,
    #[prost(uint64, tag="6")]
    pub write_version: u64,
}
// @@protoc_insertion_point(module)
