import { useState } from 'react';
import { usePetsContract } from './chains/ethereum/usePetsContract';
import { usePetActions } from './chains/solana/usePetActions';
import { usePetsConfig } from '../contexts/PetsConfigContext';
import { useActiveChain } from './useActiveChain';
import { NoActiveChainError } from '../utils/pets';

export interface CreatePetArgs {
    name: string;
    /** Solana only — ignored on EVM (DNA is generated by the contract / VRF). */
    dna?: bigint | number | string;
    /** Solana only — ignored on EVM. */
    rarity?: number;
}

export interface PetMutationResult<TArgs> {
    isSupported: boolean;
    mutate: (args: TArgs) => Promise<void>;
    isPending: boolean;
    error: Error | null;
    reset: () => void;
    /** EVM tx hash (0x…) or Solana signature, once submitted. */
    hash?: string | undefined;
}

export function useCreatePet(): PetMutationResult<CreatePetArgs> {
    const chain = useActiveChain();
    const { evm } = usePetsConfig();

    const evmHook = usePetsContract({
        contractAddress: evm?.contractAddress,
        abi: evm?.abi ?? [],
        enabled: chain.kind === 'evm',
    });
    const solanaActions = usePetActions();

    const [localError, setLocalError] = useState<Error | null>(null);

    const mutate = async (args: CreatePetArgs) => {
        if (chain.kind === 'none') throw new NoActiveChainError('create');

        try {
            setLocalError(null);
            if (chain.kind === 'evm') {
                evmHook.createRandomPet(args.name);
                return;
            }
            await solanaActions.createStarterPet.mutateAsync({
                name: args.name,
                dna: args.dna ?? 0n,
                rarity: args.rarity ?? 1,
            });
        } catch (err) {
            const error = err instanceof Error ? err : new Error(String(err));
            setLocalError(error);
            throw error;
        }
    };

    const reset = () => {
        setLocalError(null);
        solanaActions.createStarterPet.reset();
    };

    const isPending =
        chain.kind === 'evm'
            ? evmHook.isPending
            : solanaActions.createStarterPet.isPending;

    const error =
        localError ??
        (chain.kind === 'evm'
            ? (evmHook.writeError as Error | null) ?? null
            : (solanaActions.createStarterPet.error as Error | null) ?? null);

    const hash =
        chain.kind === 'evm'
            ? (evmHook.hash as string | undefined)
            : (solanaActions.createStarterPet.data as string | undefined);

    return { isSupported, mutate, isPending, error, reset, hash };
}
