// Shared contract between services/indexer-go (server) and the Node backend (client).
// Node loads this file at runtime via @grpc/proto-loader; Go stubs are generated into
// services/indexer-go/pb with `buf generate` (see services/indexer-go/buf.gen.yaml).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: cryptopets.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameDataService_GetPetState_FullMethodName  = "/cryptopets.GameDataService/GetPetState"
	GameDataService_EstimateWin_FullMethodName  = "/cryptopets.GameDataService/EstimateWin"
	GameDataService_VerifyBattle_FullMethodName = "/cryptopets.GameDataService/VerifyBattle"
)

// GameDataServiceClient is the client API for GameDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameDataServiceClient interface {
	// RAM read from the write-through roster cache (coherent because
	// indexer-go is the sole writer of pet_roster after promotion). Returns
	// UNAVAILABLE until warm-up completes — callers fall back to their own
	// database read.
	GetPetState(ctx context.Context, in *PetRequest, opts ...grpc.CallOption) (*PetResponse, error)
	// Pre-fight win estimate (plan §3.3): runs the round-based combat sim over
	// many seeds for pet_id1 vs pet_id2 (both read from the warm roster cache)
	// and returns pet_id1's win probability. UNAVAILABLE until the cache is warm.
	EstimateWin(ctx context.Context, in *WinRequest, opts ...grpc.CallOption) (*WinResponse, error)
	// Independent recomputation of a backend-authoritative battle
	// (docs/battle-protocol.md §F). Takes everything needed to
	// rerun the fight and the progression composition — no database, no cache,
	// no chain state — so a mismatch against the TypeScript engine's own result
	// means the two implementations disagree, not that either read something
	// different. Release safety only: this does not constrain an operator who
	// controls both processes (see the architecture doc's "what the Go verifier
	// is for" section). Never wired to any state-mutating path.
	VerifyBattle(ctx context.Context, in *VerifyBattleRequest, opts ...grpc.CallOption) (*VerifyBattleResponse, error)
}

type gameDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameDataServiceClient(cc grpc.ClientConnInterface) GameDataServiceClient {
	return &gameDataServiceClient{cc}
}

func (c *gameDataServiceClient) GetPetState(ctx context.Context, in *PetRequest, opts ...grpc.CallOption) (*PetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PetResponse)
	err := c.cc.Invoke(ctx, GameDataService_GetPetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameDataServiceClient) EstimateWin(ctx context.Context, in *WinRequest, opts ...grpc.CallOption) (*WinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WinResponse)
	err := c.cc.Invoke(ctx, GameDataService_EstimateWin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameDataServiceClient) VerifyBattle(ctx context.Context, in *VerifyBattleRequest, opts ...grpc.CallOption) (*VerifyBattleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyBattleResponse)
	err := c.cc.Invoke(ctx, GameDataService_VerifyBattle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameDataServiceServer is the server API for GameDataService service.
// All implementations must embed UnimplementedGameDataServiceServer
// for forward compatibility.
type GameDataServiceServer interface {
	// RAM read from the write-through roster cache (coherent because
	// indexer-go is the sole writer of pet_roster after promotion). Returns
	// UNAVAILABLE until warm-up completes — callers fall back to their own
	// database read.
	GetPetState(context.Context, *PetRequest) (*PetResponse, error)
	// Pre-fight win estimate (plan §3.3): runs the round-based combat sim over
	// many seeds for pet_id1 vs pet_id2 (both read from the warm roster cache)
	// and returns pet_id1's win probability. UNAVAILABLE until the cache is warm.
	EstimateWin(context.Context, *WinRequest) (*WinResponse, error)
	// Independent recomputation of a backend-authoritative battle
	// (docs/battle-protocol.md §F). Takes everything needed to
	// rerun the fight and the progression composition — no database, no cache,
	// no chain state — so a mismatch against the TypeScript engine's own result
	// means the two implementations disagree, not that either read something
	// different. Release safety only: this does not constrain an operator who
	// controls both processes (see the architecture doc's "what the Go verifier
	// is for" section). Never wired to any state-mutating path.
	VerifyBattle(context.Context, *VerifyBattleRequest) (*VerifyBattleResponse, error)
	mustEmbedUnimplementedGameDataServiceServer()
}

// UnimplementedGameDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameDataServiceServer struct{}

func (UnimplementedGameDataServiceServer) GetPetState(context.Context, *PetRequest) (*PetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPetState not implemented")
}
func (UnimplementedGameDataServiceServer) EstimateWin(context.Context, *WinRequest) (*WinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EstimateWin not implemented")
}
func (UnimplementedGameDataServiceServer) VerifyBattle(context.Context, *VerifyBattleRequest) (*VerifyBattleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyBattle not implemented")
}
func (UnimplementedGameDataServiceServer) mustEmbedUnimplementedGameDataServiceServer() {}
func (UnimplementedGameDataServiceServer) testEmbeddedByValue()                         {}

// UnsafeGameDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameDataServiceServer will
// result in compilation errors.
type UnsafeGameDataServiceServer interface {
	mustEmbedUnimplementedGameDataServiceServer()
}

func RegisterGameDataServiceServer(s grpc.ServiceRegistrar, srv GameDataServiceServer) {
	// If the following call panics, it indicates UnimplementedGameDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameDataService_ServiceDesc, srv)
}

func _GameDataService_GetPetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameDataServiceServer).GetPetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameDataService_GetPetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameDataServiceServer).GetPetState(ctx, req.(*PetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameDataService_EstimateWin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameDataServiceServer).EstimateWin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameDataService_EstimateWin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameDataServiceServer).EstimateWin(ctx, req.(*WinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameDataService_VerifyBattle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyBattleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameDataServiceServer).VerifyBattle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameDataService_VerifyBattle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameDataServiceServer).VerifyBattle(ctx, req.(*VerifyBattleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameDataService_ServiceDesc is the grpc.ServiceDesc for GameDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cryptopets.GameDataService",
	HandlerType: (*GameDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPetState",
			Handler:    _GameDataService_GetPetState_Handler,
		},
		{
			MethodName: "EstimateWin",
			Handler:    _GameDataService_EstimateWin_Handler,
		},
		{
			MethodName: "VerifyBattle",
			Handler:    _GameDataService_VerifyBattle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cryptopets.proto",
}
